"""Cria tabelas empresas e certificados

Revision ID: 4effebee436c
Revises: 624e3a4025bc
Create Date: 2026-07-10 04:58:11.194851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4effebee436c'
down_revision: Union[str, Sequence[str], None] = '624e3a4025bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_fantasia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inscricao_estadual', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logradouro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato_telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('regime_tributario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('csc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('csc_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_empresas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('certificados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_criptografada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validade', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificados_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificados_empresa_id'))

    op.drop_table('certificados')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
