"""make empresa_id nullable

Revision ID: 8184e274f13d
Revises: 73add2dd4ad5
Create Date: 2026-07-17 16:16:44.994095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8184e274f13d'
down_revision: Union[str, Sequence[str], None] = '73add2dd4ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_empresa_id'))

    op.drop_table('notas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_token_integracao'), ['token_integracao'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_token_integracao'))

    op.create_table('notas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=2), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('chave_acesso', sa.VARCHAR(length=44), nullable=True),
    sa.Column('numero', sa.INTEGER(), nullable=True),
    sa.Column('serie', sa.INTEGER(), nullable=True),
    sa.Column('valor_total', sa.FLOAT(), nullable=False),
    sa.Column('json_venda', sa.VARCHAR(), nullable=False),
    sa.Column('payload_enviado', sa.VARCHAR(), nullable=True),
    sa.Column('resposta_integradora', sa.VARCHAR(), nullable=True),
    sa.Column('xml_url', sa.VARCHAR(), nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=False),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###
