"""Cria tabela regras fiscais

Revision ID: a93ce84b4d7c
Revises: 4effebee436c
Create Date: 2026-07-10 08:54:49.970616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a93ce84b4d7c'
down_revision: Union[str, Sequence[str], None] = '4effebee436c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regras_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cfop', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('ncm_padrao', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('origem_icms', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('cst_csosn', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('icms_aliquota', sa.Float(), nullable=False),
    sa.Column('pis_cst', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('pis_aliquota', sa.Float(), nullable=False),
    sa.Column('cofins_cst', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('cofins_aliquota', sa.Float(), nullable=False),
    sa.Column('padrao', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regras_fiscais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regras_fiscais_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regras_fiscais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regras_fiscais_empresa_id'))

    op.drop_table('regras_fiscais')
    # ### end Alembic commands ###
