"""Add certificado fields to Empresa

Revision ID: fdedffc7d917
Revises: 8184e274f13d
Create Date: 2026-07-24 14:49:59.051823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdedffc7d917'
down_revision: Union[str, Sequence[str], None] = '8184e274f13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificado_base64', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('certificado_senha', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('certificado_vencimento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('certificado_emissor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('certificado_sujeito', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('certificado_sujeito')
        batch_op.drop_column('certificado_emissor')
        batch_op.drop_column('certificado_vencimento')
        batch_op.drop_column('certificado_senha')
        batch_op.drop_column('certificado_base64')

    # ### end Alembic commands ###
